---
title: Colton English's home page
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: colton@sparksis.com
description: Just a quick site to host my resume.
baseurl: ''
url: https://coltonenglish.me
github_username: coltonenglish
google_analytics: G-QXDQBJMKSY
theme: minima
plugins:
- jekyll-sitemap
